### ISSUE TITLE
Fix CommandLineRunner to run properly

### ISSUE THREAD

**Issue by janimaenpaa** [Team-Tiikeri/kysely-backend#11]
Crashes when trying to run uncommented.

**Comment by SamuliPeltonen** [comment]
Seems to work when running without logger, that probably is the root cause for the crashes. Questionnaire-object's attributes can be printed to terminal when the logger stays commented.

**Comment by SamuliPeltonen** [comment]
b83fe125eedf89ca7f5417018919ef4448f1cacc
